queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - and:
        - "base=master"
        - "#review-threads-unresolved=0"
        - "#changes-requested-reviews-by=0"
        - "#approved-reviews-by>=1"
        - "label!=do-not-merge"
        - "label!=mergify-ignore"
    actions:
      queue:
        name: default
        method: merge

  - name: Add merge train label
    conditions:
      - "queue-position >= 0"
    actions:
      comment:
          message: |
            This PR has been added to the merge queue, and will be merged soon.
      label:
        add:
          - on-merge-train

  - name: Remove merge train label
    conditions:
      - "queue-position = -1"
    actions:
      label:
        remove:
          - on-merge-train

  - name: Ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: Hey @{{author}}! This PR has merge conflicts. Please fix them before continuing review.
      label:
        add:
          - conflict

  - name: Remove conflicts label when conflicts gone
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict

  - name: Notify author when added to merge queue
    conditions:
      - "check-pending=Queue: Embarked in merge train"
    actions:
      comment:
        message: |
          This PR is next in line to be merged, and will be merged as soon as checks pass.

  - name: Notify author when merge queue failed
    conditions:
      - "check-failure=Queue: Embarked in merge train"
    actions:
      comment:
        message: |
          Merge failed. Please see automated check logs for more details.
