queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: Ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: Hey @{{author}}! This PR has merge conflicts. Please fix them before continuing review.
      label:
        add:
          - conflict

  - name: Remove conflicts label when conflicts gone
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict

  - name: Notify author when merge queue failed
    conditions:
      - 'check-failure=Queue: Embarked in merge train'
    actions:
      comment:
        message: |
          Merge failed. Please see automated check logs for more details.

  - name: automatic update prs
    conditions:
      - -conflict
      - -draft
      - label!="do-not-merge"
      - 'base=master'
    actions:
      update:

  - name: Say hi to contributors if they are not part of the regularcontributors team
    conditions:
      - author!=@regularcontributors
    actions:
      comment:
        message: |
          Thanks for creating the PR! We're stoked to see you building on Optimism.
          Please give our team about a week to review your PR :)

  - name: Say thanks
    conditions:
      - author!=@regularcontributors
      - merged
    actions:
      comment:
        message: |
          Your token has been merged.  Consider joining our discord.  Follow us on twitter.  Make sure to drink plenty of water.
