FROM node:22.14.0-alpine3.21

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN corepack enable && corepack prepare pnpm@8.6.0 --activate

RUN pnpm install --frozen-lockfile --ignore-scripts

COPY . /app

CMD [ "pnpm", "start-bot" ]

EXPOSE 7300
