[tools]
node = "18.18.0"

[hooks]
# Enabling corepack will install the `pnpm` package manager specified in package.json
postinstall = "npx corepack enable"

[settings]
# Needs to be enabled for hooks to work
experimental = true