name: Generate Token List

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  generate:
    name: generate
    if: |
      github.event.head_commit.committer.username != 'github-actions[bot]'
        && github.repository == 'ethereum-optimism/ethereum-optimism.github.io'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Patch token list version
        run: |
          git config --global user.email "mergify[bot]@users.noreply.github.com"
          git config --global user.name "mergify[bot]"
          npm version patch

      - name: Generate token list
        run: |
          pnpm generate:ci

      - name: Commit token list
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'bot(ci): generate token list'
          file_pattern: optimism.tokenlist.json
