name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: 'This issue has been automatically marked as stale and will be closed in 7 days if no updates'
          stale-pr-message: 'This pr has been automatically marked as stale and will be closed in 7 days if no updates'
          close-issue-message: 'This issue was closed as stale.  Please reopen if this is a mistake'
          close-pr-message: 'This PR was closed as stale.  Please reopen if this is a mistake'
          days-before-issue-stale: 7
          days-before-pr-stale: 7
          days-before-issue-close: 7
          days-before-pr-close: 7
